name: PetLives
version: ${project.version}
main: lol.hyper.petlives.PetLives
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/petlives.91822/
description: Give your pet lives and revive them if they die.
commands:
  petlives:
    usage: /petlives
    permission: petlives.command
permissions:
  petlives.command:
    description: Main permission node to access /petlives.
    default: true
  petlives.command.setlives:
    description: Main permission node to access /petlives setlives.
    default: op
  petlives.command.check:
    description: Main permission node to access /petlives check.
    default: true
  petlives.command.deadpets:
    description: Main permission node to access /petlives deadpets.
    default: true
  petlives.command.revive:
    description: Main permission node to access /petlives revive.
    default: true