name: PetLives
version: ${project.version}
main: lol.hyper.petlives.PetLives
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/petlives.91822/
description: Give your pet lives and revive them if they die.
commands:
  petlives:
    usage: /petlives
libraries:
  - org.json:json:20211205
  - lol.hyper:github-release-api:1.0.1